# Generated by Django 4.0.6 on 2022-09-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, upload_to='categories/', verbose_name='Иконка')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-isActive'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активность')),
                ('isStock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('isFeatured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('image', models.ImageField(blank=True, upload_to='items/', verbose_name='Изображение')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-isActive'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активность')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cafe.item', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['-isActive'],
            },
        ),
    ]
