# Generated by Django 4.0.6 on 2022-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, upload_to='categories/', verbose_name='Иконка'),
        ),
    ]
