# Generated by Django 4.2 on 2023-04-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_cafe_category_item_cafe_alter_cafe_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cafe',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Имя кафе')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to='cafe.cafe', verbose_name='кафе')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu', to='cafe.menu', verbose_name='меню'),
            preserve_default=False,
        ),
    ]
